# Generated by Django 5.2 on 2025-04-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_tag_bookmark_class_bookmark_user_lesson_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='ClassSession',
            new_name='Session',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='classLesson',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('title', 'course')},
        ),
    ]
