# Generated by Django 5.2 on 2025-04-27 07:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_user_avatar_alter_classcategory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
