# Generated by Django 5.2 on 2025-04-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_students_user_role_alter_course_bookmark_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('tiep_tan', 'Tiếp Tân'), ('hlv', 'Hlv'), ('hoc-vien', 'Hoc Vien')], default='hoc-vien', max_length=20, null=True),
        ),
    ]
