# Generated by Django 5.2 on 2025-05-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
