# Generated by Django 5.2 on 2025-05-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='courses',
            new_name='course',
        ),
    ]
