# Generated by Django 5.2 on 2025-05-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_news_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type_news',
            field=models.CharField(default='news', max_length=100),
        ),
    ]
