# Generated by Django 5.2 on 2025-05-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_expodevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expodevice',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
