# Generated by Django 5.2 on 2025-05-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
