# Generated by Django 5.2 on 2025-05-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.IntegerField(),
        ),
    ]
