# Generated by Django 5.2 on 2025-06-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
    ]
