# Generated by Django 5.2 on 2025-06-02 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_remove_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course'),
        ),
    ]
