# Generated by Django 5.2 on 2025-06-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_session_class_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='type_news',
            field=models.CharField(choices=[('work out', 'Work Out'), ('nutrition', 'Nutrition'), ('event', 'Event'), ('news', 'News')], default='news', max_length=20),
        ),
    ]
