# Generated by Django 5.2 on 2025-06-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_news_type_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
